server:
  port: 8080
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:shopItems
    username: sa
    driver-class-name: org.h2.Driver


  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer

    consumer:
      bootstrap-servers:
        - localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-deserializer: org.apache.kafka.common.serialization.LongSerializer
      auto-offset-reset: earliest
      group-id: items-group


